version: '3.8'
services:
  rsi-mqtt:
    build: .
    container_name: rsi-mqtt-service
    environment:
      - LOGLEVEL=INFO
    volumes:
      - ./config.json:/app/config.json
    ports:
      - "888:888"
